# Generated by Django 2.2 on 2021-06-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0003_auto_20210612_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_messages', to='solo_app.User'),
        ),
    ]
