# Generated by Django 2.2 on 2021-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_app', '0004_message_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='liked_messages', to='solo_app.User'),
        ),
    ]
